---
swagger: "2.0"
info:
  description: "yes"
  version: "1.0.0"
  title: "Hack for the Future"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "127.0.0.1"
basePath: "/api/"
tags:
- name: "workspaces"
  description: "Everything about your workspaces"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "topics"
  description: "Everything about your topics"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "materials"
  description: "Everything about your materials"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
- name: "tasks"
  description: "Everything about your tasks"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
paths:
  /workspaces:
    get:
      tags:
      - "workspaces"
      summary: "Lists all workspaces"
      operationId: "workspaces_get"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Workspace"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
    post:
      tags:
      - "workspaces"
      summary: "Create new workspace, accepts workspace name"
      operationId: "workspaces_post"
      consumes:
      - "text"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Workspace"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
  /workspaces/{workspaceId}:
    get:
      tags:
      - "workspaces"
      summary: "Get specified workspace by its UUID"
      operationId: "workspaces_workspace_id_get"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Workspace"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
    put:
      tags:
      - "workspaces"
      summary: "Update specified workspace by its UUID"
      operationId: "workspaces_workspace_id_put"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Workspace"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
    delete:
      tags:
      - "workspaces"
      summary: "Delete specified workspace by its UUID"
      operationId: "workspaces_workspace_id_delete"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
  /workspaces/{workspaceId}/topics:
    get:
      tags:
      - "workspaces"
      summary: "Get all topics of the workspace specified by UUID"
      operationId: "workspaces_workspace_id_topics_get"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Topic"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
    post:
      tags:
      - "workspaces"
      summary: "Create new topic, returns the topic"
      operationId: "workspaces_workspace_id_topics_post"
      consumes:
      - "text"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Topic"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
  /workspaces/{workspaceId}/topics/{topicId}:
    get:
      tags:
      - "topics"
      summary: "Return specified topic"
      operationId: "workspaces_workspace_id_topics_topic_id_get"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Topic"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.topics_controller"
    put:
      tags:
      - "topics"
      summary: "Update topic specified by id, return topic"
      operationId: "workspaces_workspace_id_topics_topic_id_put"
      consumes:
      - "text"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Topic"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.topics_controller"
    delete:
      tags:
      - "workspaces"
      summary: "Delete specified topic"
      operationId: "workspaces_workspace_id_topics_topic_id_delete"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.workspaces_controller"
  /workspaces/{workspaceId}/topics/{topicId}/materials:
    get:
      tags:
      - "materials"
      summary: "Get all materials for a topic"
      operationId: "workspaces_workspace_id_topics_topic_id_materials_get"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Material"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.materials_controller"
    post:
      tags:
      - "materials"
      summary: "Create new material for the specified topic"
      operationId: "workspaces_workspace_id_topics_topic_id_materials_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Material"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.materials_controller"
  /workspaces/{workspaceId}/topics/{topicId}/materials/{materialId}:
    get:
      tags:
      - "materials"
      summary: "Return specified material"
      operationId: "workspaces_workspace_id_topics_topic_id_materials_material_id_get"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      - name: "materialId"
        in: "path"
        description: "ID of material"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Material"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.materials_controller"
    put:
      tags:
      - "materials"
      summary: "Update material specified by id, return material"
      operationId: "workspaces_workspace_id_topics_topic_id_materials_material_id_put"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      - name: "materialId"
        in: "path"
        description: "ID of material"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Material"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.materials_controller"
    delete:
      tags:
      - "materials"
      summary: "Delete specified topic"
      operationId: "workspaces_workspace_id_topics_topic_id_materials_material_id_delete"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      - name: "materialId"
        in: "path"
        description: "ID of material"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.materials_controller"
  /workspaces/{workspaceId}/topics/{topicId}/tasks:
    get:
      tags:
      - "tasks"
      summary: "Get all tasks for a topic"
      operationId: "workspaces_workspace_id_topics_topic_id_tasks_get"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Task"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.tasks_controller"
    post:
      tags:
      - "tasks"
      summary: "Create new task for the specified topic"
      operationId: "workspaces_workspace_id_topics_topic_id_tasks_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Task"
        "405":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.tasks_controller"
  /workspaces/{workspaceId}/topics/{topicId}/tasks/{taskId}:
    get:
      tags:
      - "tasks"
      summary: "Return specified task"
      operationId: "workspaces_workspace_id_topics_topic_id_tasks_task_id_get"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      - name: "taskId"
        in: "path"
        description: "ID of task"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Task"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.tasks_controller"
    put:
      tags:
      - "tasks"
      summary: "Update task specified by id, return task"
      operationId: "workspaces_workspace_id_topics_topic_id_tasks_task_id_put"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      - name: "taskId"
        in: "path"
        description: "ID of task"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/Material"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.tasks_controller"
    delete:
      tags:
      - "materials"
      summary: "Delete specified task"
      operationId: "workspaces_workspace_id_topics_topic_id_tasks_task_id_delete"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      - name: "taskId"
        in: "path"
        description: "ID of task"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.materials_controller"
  /workspaces/{workspaceId}/topics/{topicId}/tasks/{taskId}/submit:
    post:
      tags:
      - "tasks"
      summary: "Submit the completed task"
      operationId: "workspaces_workspace_id_topics_topic_id_tasks_task_id_submit_post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - name: "workspaceId"
        in: "path"
        description: "ID of workspace"
        required: true
        type: "string"
      - name: "topicId"
        in: "path"
        description: "ID of topic"
        required: true
        type: "string"
      - name: "taskId"
        in: "path"
        description: "ID of task"
        required: true
        type: "string"
      responses:
        "200":
          description: "OK"
          schema:
            type: "array"
            items:
              type: "boolean"
        "400":
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.tasks_controller"
definitions:
  Answer:
    type: "object"
    properties:
      isCorrect:
        type: "boolean"
      text:
        type: "string"
      explanation:
        type: "string"
    example:
      text: "text"
      explanation: "explanation"
      isCorrect: true
  Topic:
    type: "object"
    properties:
      uuid:
        type: "string"
      name:
        type: "string"
    example:
      name: "name"
      uuid: "uuid"
  Task:
    type: "object"
    properties:
      uuid:
        type: "string"
      link:
        type: "string"
    example:
      link: "link"
      uuid: "uuid"
  Question:
    type: "object"
    properties:
      uuid:
        type: "string"
      questionText:
        type: "string"
      answers:
        type: "array"
        items:
          $ref: "#/definitions/Answer"
    example:
      answers:
      - text: "text"
        explanation: "explanation"
        isCorrect: true
      - text: "text"
        explanation: "explanation"
        isCorrect: true
      uuid: "uuid"
      questionText: "questionText"
  User:
    type: "object"
    properties:
      uuid:
        type: "string"
      name:
        type: "string"
    example:
      name: "name"
      uuid: "uuid"
  Material:
    type: "object"
    properties:
      uuid:
        type: "string"
      name:
        type: "string"
      link:
        type: "string"
      questions:
        type: "array"
        items:
          $ref: "#/definitions/Question"
      tasks:
        type: "array"
        items:
          $ref: "#/definitions/Task"
      topics:
        type: "array"
        items:
          $ref: "#/definitions/Topic"
    example:
      topics:
      - name: "name"
        uuid: "uuid"
      - name: "name"
        uuid: "uuid"
      name: "name"
      link: "link"
      questions:
      - answers:
        - text: "text"
          explanation: "explanation"
          isCorrect: true
        - text: "text"
          explanation: "explanation"
          isCorrect: true
        uuid: "uuid"
        questionText: "questionText"
      - answers:
        - text: "text"
          explanation: "explanation"
          isCorrect: true
        - text: "text"
          explanation: "explanation"
          isCorrect: true
        uuid: "uuid"
        questionText: "questionText"
      uuid: "uuid"
      tasks:
      - link: "link"
        uuid: "uuid"
      - link: "link"
        uuid: "uuid"
  Workspace:
    type: "object"
    properties:
      uuid:
        type: "string"
      name:
        type: "string"
      admin:
        $ref: "#/definitions/User"
      students:
        type: "array"
        items:
          $ref: "#/definitions/User"
      materials:
        type: "array"
        items:
          $ref: "#/definitions/Material"
    example:
      materials:
      - topics:
        - name: "name"
          uuid: "uuid"
        - name: "name"
          uuid: "uuid"
        name: "name"
        link: "link"
        questions:
        - answers:
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          uuid: "uuid"
          questionText: "questionText"
        - answers:
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          uuid: "uuid"
          questionText: "questionText"
        uuid: "uuid"
        tasks:
        - link: "link"
          uuid: "uuid"
        - link: "link"
          uuid: "uuid"
      - topics:
        - name: "name"
          uuid: "uuid"
        - name: "name"
          uuid: "uuid"
        name: "name"
        link: "link"
        questions:
        - answers:
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          uuid: "uuid"
          questionText: "questionText"
        - answers:
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          - text: "text"
            explanation: "explanation"
            isCorrect: true
          uuid: "uuid"
          questionText: "questionText"
        uuid: "uuid"
        tasks:
        - link: "link"
          uuid: "uuid"
        - link: "link"
          uuid: "uuid"
      name: "name"
      admin:
        name: "name"
        uuid: "uuid"
      students:
      - name: "name"
        uuid: "uuid"
      - name: "name"
        uuid: "uuid"
      uuid: "uuid"
